language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-superfrontend' ]; then cd .. && eval "mv $currentfolder generator-superfrontend" && cd generator-superfrontend; fi

